##############################################
# +----------------------------------------+ #
# |            Item Update List            | #
# +----------------------------------------+ #
##############################################

update:

  # Toggle automatic updates of certain items if used.
  auto-update:
    armour: true

  "masterwork:masterwork_chestplate": "masterwork:masterwork_chestplate"
  "masterwork:masterwork_helmet": "masterwork:masterwork_helmet"

##############################################
# +----------------------------------------+ #
# |          Item configurations           | #
# +----------------------------------------+ #
##############################################

items:

  telekinetic-wand:
    blacklist:
      - CHEST
      - SHULKER
      - BARREL
      - FURNACE
      - DROPPER
      - DISPENSER
      - HOPPER
      - SMOKER
      - BREWING_STAND
      - DECORATED_POT
      - JUKEBOX

  architects-wand:
    CraftStair:
      - direction
      - half
      - stair_shape
      - waterlogged
    CraftWall:
      - wall_height
      - center
      - waterlogged
    CraftFence:
      - connection
      - waterlogged
    CraftIronBars:
      - connection
    CraftStainedGlassPane:
      - connection
    CraftLever:
      - direction
      - attachment
      - powered
    CraftTripWireHook:
      - direction
      - attached
      - powered
    CraftBed:
      - direction
      - bed_part
    CraftBigDripleaf:
      - dripleaf_tilt
      - direction
    CraftButton:
      - direction
      - powered
    CraftTrapDoor:
      - open
    CraftDoor:
      - open

  creeper_bow:
    # Chance for any shot arrow will be explosive.
    explosive-chance: 0.15
    # Should explosive arrows damage blocks?
    # When TRUE, explosive arrows destroy blocks in areas where the firer has permission to destroy.
    enable-explosion-damage: TRUE
    # Set explosion strength.
    # 4.0 is around a standard TNT explosion.
    explosion-strength: 4.0
    # Velocity multiplier of explosive arrows.
    # 1.0 is default, higher values make arrows faster.
    velocity-multiplier: 1.0
    # Sound effect for explosive arrows.
    # Leave empty for no sound.
    sound-effect: entity.creeper.primed
    # Particle trail effects for explosive arrows.
    # Leave empty for no particles.
    particle-effect: smoke

  creeper_rocket:
    refill-item: "dungeons:charged_gunpowder"
    max-usages: 256
    usages-per-refill: 4

  kraken-armour:
    cooldown: 60 # in seconds
    assistant-commands:
    - "mm test cast Kraken_Summon_Dead_Adventurer_Assistant"
    - "mm test cast Kraken_Summon_Tentacle_Assistant"
    assistants:
      Kraken_Dead_Adventurer_Assistant:
        amount: 3
        radius: 8
      Kraken_Tentacle_Assistant:
        amount: 1
        radius: 8

  kraken-sabre:
    lightning-chance: 1.0
    lightning-damage: 5

  banana-sabre:
    slip-chance: 1.0
    slip-strength: 5

  halloween:
    # Chance for a trick or treat roll to happen.
    activation-chance: 0.15
    # Controls the split between good and bad effects if activated.
    # Values above 0.50 favor Treats. Values below 0.50 favor Tricks.
    ability-balance: 0.50
    # Which tools should activate which ability sets.
    tool-activators:
      - the_gouger
      - the_cleaver
      - the_extractor
      - the_harvester
    weapon-activators:
      - the_carver
      - the_cleaver
    # Possible item (custom items supported) drops for the following abilities:
    # Ooh! A piece of candy, Piñata.
    treat-drops:
      - candy1
      - candy2
      - candy3
      - candy4
      - candy5
      - candy6
      - candy7
      - candy8
      - candy9
      - candy10
      # Possible items to drop when Jack o'Pot triggers.
    jack-o-pot-drops:
      - DIAMOND
      - EMERALD
      - GOLD_INGOT
    # Amount of EXP the Spirit Orbs treat should create.
    spirit-orbs-exp: 50
    # How many extra blocks of reach a player gets from the Long Limbed treat.
    reach-amount: 3
    # What sounds the Scary Sounds trick can play.
    scary-sounds:
      - "entity.creeper.primed"
    # How many bats should the trick Bat Swarm spawns.
    bat-swarm-amount: 5
    # Negative potion effects applied for the following tricks:
    # Grave Grasp.
    # Duration is in ticks.
    negative-potion-effects:
     - type: slowness
       duration: 60
       amplifier: 3
     - type: mining_fatigue
       duration: 60
       amplifier: 3
    # Positive potion effects applied for the following tricks:
    # Gourd Guard.
    # Duration is in ticks.
    positive-potion-effects:
      - type: absorption
        duration: 60
        amplifier: 1
    # Hunger and saturation restored by the Midnight Snack treat.
    # Food has to be an integer.
    midnight-snack-food: 6
    # Saturation has to be a double.
    midnight-snack-saturation: 4.0

necromancer-armour:
  # How many revives a player can get from the armour before dying.
  max-revives: 1
  # List of mobs that will ignore a player in Necromancer armour.
  ignored-mobs:
    - CAMEL_HUSK
    - DROWNED
    - ZOGLIN
    - ZOMBIE
    - ZOMBIE_HORSE
    - ZOMBIE_NAUTILUS
    - ZOMBIE_VILLAGER
    - ZOMBIFIED_PIGLIN
    - BOGGED
    - PARCHED
    - SKELETON
    - SKELETON_HORSE
    - STRAY
    - WITHER_SKELETON
    - PHANTOM
  # Possible assistants that can spawn when a wearer kills an entity.
  assistants:
    Necromancer_Assistant:
      spawn-chance: 0.25
      amount: 1

##############################################
# +----------------------------------------+ #
# |                Vouchers                | #
# +----------------------------------------+ #
##############################################

# Section to edit values related to redeeming voucher items.

vouchers:
  # What ItemsAdder namespace are the vouchers kept in?
  namespace: "vouchers"
  # Item path must start with this (case-insensitive).
  # For example: vouchers:prefixbear
  path-prefix: "prefix"
  # How to build the permission from the derived key, this is what users are assigned after redeeming.
  # %key% is replaced after normalisation.
  permission-format: "chatprefix.%key%"
  # What particle should play when a prefix is successfully redeemed.
  # Leave empty for no particles.
  play-particle: "ENCHANT"
  # What sound should play when a prefix is successfully redeemed.
  # Leave empty for no sound.
  success-sound: "entity.experience_orb.pickup"
  # What sound should play if a prefix is unsuccessfully redeemed.
  # Leave empty for no sound.
  fail-sound: "entity.villager.no"

##############################################
# +----------------------------------------+ #
# |          Custom Potion Config          | #
# +----------------------------------------+ #
##############################################

# Here is where you can add new potion variants of VANILLA status effects.
# See the example block below on how to format the file.
# Please note that this plugin only supports ItemsAdder as a dependency, and uses their base items to apply effects.
# See below for a configuration explanation and some examples of potions of hunger.

# custom_potions:                   # Namespace of the item.
#   custom_drinkable_potion:        # Name of the item.
#     form: DRINK                   # Potion type, accepts DRINK, SPLASH, LINGERING.
#     effect: HUNGER                # Potion effect, accepts PotionEffectType from Paper API.
#     amplifier: 0                  # Severity of potion, 0 is regular strength - higher numbers are stronger.
#     duration: 24000               # Length of potion effect, in ticks. 20 ticks = 1 second.

potions:

  custom_potions:

    hunger1:
      form: DRINK
      effect: HUNGER
      amplifier: 0
      duration: 2400

    hunger2:
      form: DRINK
      effect: HUNGER
      amplifier: 1
      duration: 1200

    hunger3:
      form: DRINK
      effect: HUNGER
      amplifier: 0
      duration: 4800

    hunger4:
      form: SPLASH
      effect: HUNGER
      amplifier: 0
      duration: 2400

    hunger5:
      form: LINGERING
      effect: HUNGER
      amplifier: 0
      duration: 1200


##############################################
# +----------------------------------------+ #
# |                Language                | #
# +----------------------------------------+ #
##############################################

# This section has editable language configurations for plugin messages.

messages:
  prefix: "<bold><red>U</red><white>L</white> Dungeons <dark_gray>» </dark_gray></bold>"
  reload: "<dark_green>Plugin reloaded."
  tool-broken: "<red>This tool is broken and needs repair to continue using it.</red>"
  armour-broken: "<yellow>This armour is broken and you will take double damage until it is repaired.</yellow>"
  voucher-unlocked: "<green>Voucher successfully redeemed!</green>"
  voucher-owned: "<yellow>You have already redeemed this voucher!</yellow>"
  voucher-failed: "<red>Error with redeeming voucher. Please contact Staff.</red>"
  update-no-item: "<red>You must hold an item to update in your main hand.</red>"
  update-no-custom-item: "<red>This is not a custom item and can't be updated.</red>"
  update-updating: "<gray>Updating item...</gray>"
  update-enchants: "<gray>Adding enchants...</gray>"
  update-damage: "<gray>Applying damage...</gray>"
  update-trim: "<gray>Applying trim...</gray>"
  update-done: "<gray>Done.</gray>"
  update-error: "<red>This item can't be updated.</red>"
      