name: UnitedItems
version: '${project.version}'
main: org.unitedlands.items.UnitedItems
api-version: 1.21
authors: [ Litning11 ]
contributors: [ Maroon28, Theriel_ ]
depend: [NBTAPI, Towny ]
commands:
  uniteditems:
    description: General UnitedItems commands
  updateitem:
    description: Updates legacy items to new versions.